name: flutter_bugfender
description: Flutter plugin to enable Bugfender reporting (with Java and Swift support).
version: 1.3.1
homepage: https://github.com/orestesgaolin/BugfenderSDK-Flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.ninja.flutterbugfender
        pluginClass: FlutterBugfenderPlugin
      ios:
        pluginClass: FlutterBugfenderPlugin

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ">=2.1.0 <3.0.0"
