name: flutter_bugfender
description: Flutter plugin to enable Bugfender reporting (with Java and Swift support).
version: 1.2.0
homepage: https://github.com/bugfender/BugfenderSDK-Flutter

flutter:
  plugin:
    androidPackage: com.ninja.flutterbugfender
    pluginClass: FlutterBugfenderPlugin

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.58.0 <3.0.0"
